module.exports = {
"ENSRegistry": require('./ENSRegistry.js').default,
"Resolver": require('./Resolver.js').default,
"FIFSRegistrar": require('./FIFSRegistrar.js').default,
"Context": require('./Context.js').default,
"GSNRecipient": require('./GSNRecipient.js').default,
"IRelayHub": require('./IRelayHub.js').default,
"IRelayRecipient": require('./IRelayRecipient.js').default,
"IOUtoken": require('./IOUtoken.js').default,
"Roles": require('./Roles.js').default,
"CapperRole": require('./CapperRole.js').default,
"MinterRole": require('./MinterRole.js').default,
"PauserRole": require('./PauserRole.js').default,
"SignerRole": require('./SignerRole.js').default,
"WhitelistAdminRole": require('./WhitelistAdminRole.js').default,
"WhitelistedRole": require('./WhitelistedRole.js').default,
"Math": require('./Math.js').default,
"SafeMath": require('./SafeMath.js').default,
"ERC20": require('./ERC20.js').default,
"ERC20Burnable": require('./ERC20Burnable.js').default,
"ERC20Capped": require('./ERC20Capped.js').default,
"ERC20Detailed": require('./ERC20Detailed.js').default,
"ERC20Mintable": require('./ERC20Mintable.js').default,
"IERC20": require('./IERC20.js').default,
"StoreIOUs": require('./StoreIOUs.js').default,
"MakeIOU": require('./MakeIOU.js').default,
};